name: 'Set versions'
description: 'Sets env variables with various software versions used in the workflows'

defaults:
  run:
    shell: bash

runs:
  using: 'composite'
  steps:
    - name: "set UV version"
      run: echo "VERSION_UV=0.5.24" >> $GITHUB_ENV
    - name: "set Julia version"
      run: echo "VERSION_JULIA=1.11.2" >> $GITHUB_ENV


