name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    # needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install sphinx myst_parser myst-nb sphinxawesome-theme sphinx-togglebutton jupytext
      - name: Install local package
        run: |
          pip install -e .
      - name: Sphinx build
        run: |
          sphinx-build docs docs/_build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
