name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/set-versions

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{env.VERSION_JULIA}}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{env.VERSION_UV}}

      - name: Sphinx build
        run: |
          uv run sphinx-build docs docs/_build

#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        if: ${{ github.ref == 'refs/heads/main' }}
#        with:
#          publish_branch: gh-pages
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: docs/_build/
#          force_orphan: true
